### ISSUE TITLE
Add a default value for CustomProperties

### ISSUE THREAD

**Issue by ArieHein** [RoKotMan/AI-Custom-Event#2]
If I dont check the option to add Pipeline metadata, should either give $CustomProperties an empty / null value or add a if statement inside the try section to only send the $EventName

**Comment by kotrokot** [comment]
TrackEvent method needs a parameter of System.Collections.Generic.IDictionary type. In this approach, $CustomProperties is an object with 0 counts of keys.  I think it's correct)
